# Generated by Django 5.2 on 2025-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="name",
            field=models.CharField(max_length=155),
        ),
    ]
