# Generated by Django 5.2 on 2025-04-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_alter_command_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
