# Generated by Django 5.2 on 2025-04-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_alter_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="command",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspace.command",
            ),
        ),
    ]
