# Generated by Django 5.2 on 2025-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0004_project_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="execution_status",
            field=models.IntegerField(
                choices=[(25, "25%"), (50, "50%"), (75, "75%"), (100, "100%")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To Do"),
                    ("in_progress", "In Progress"),
                    ("code_review", "Code Review"),
                    ("done", "Already Done"),
                ],
                default="to_do",
                max_length=20,
            ),
        ),
    ]
