# Generated by Django 5.2 on 2025-05-03 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_task_execution_status_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="stage_of_execution",
            field=models.IntegerField(
                choices=[(25, "25%"), (50, "50%"), (75, "75%"), (100, "100%")],
                default="25",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="execution_status",
            field=models.IntegerField(
                default="0",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To Do"),
                    ("in_progress", "In Progress"),
                    ("code_review", "Code Review"),
                    ("done", "Already Done"),
                ],
                default="To Do",
                max_length=20,
            ),
        ),
    ]
