# Generated by Django 5.2 on 2025-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0008_alter_archive_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="link_to_solution",
            field=models.TextField(max_length=512, null=True),
        ),
    ]
