# Generated by Django 5.2 on 2025-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0009_task_link_to_solution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="link_to_solution",
            field=models.TextField(max_length=155, null=True),
        ),
    ]
