# Generated by Django 5.2 on 2025-05-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0010_alter_command_created_at_alter_task_link_to_solution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["-is_leader"]},
        ),
    ]
